import type { Metadata } from "next";
import { Aboreto, Gayathri } from "next/font/google";
import "./globals.css";
import { Instagram, Search, ShoppingBag } from "lucide-react";
import Link from "next/link";

const gayathri = Gayathri({
  variable: "--font-gayathri",
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});

const aboreto = Aboreto({
  variable: "--font-aboreto",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gayathri.variable} ${aboreto.variable}  antialiased`}>
        <header className="bg-white hidden">
          <div className="container">
            <div className="py-4 flex items-center justify-between">
              <div className="flex flex-col items-center">
                <h1 className="font-aboreto text-2xl">SUROJIDDIN</h1>
                <p className="font-aboreto text-2xl">ATTOR</p>
              </div>
              <div className="text-xl flex gap-4">
                <Link href={"/"}>MENS</Link>
                <Link href={"/"}>WOMENS</Link>
                <Link href={"/"}>TRENDS</Link>
                <Link href={"/"}>SEASONS</Link>
              </div>
              <div className="flex gap-4">
                <button className="cursor-pointer">
                  <Search width={26} height={26} strokeWidth={1.5} />
                </button>
                <button className="cursor-pointer">
                  <ShoppingBag width={26} height={26} strokeWidth={1.5} />
                </button>
                <button className="cursor-pointer">
                  <Instagram width={26} height={26} strokeWidth={1.5} />
                </button>
              </div>
            </div>
          </div>
        </header>
        <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
          {children}
        </main>
        <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center"></footer>
      </body>
    </html>
  );
}
