import type { Metadata } from "next";
import { Aboreto, Gayathri } from "next/font/google";
import "./globals.css";
import { Instagram, Search, ShoppingBag } from "lucide-react";
import Link from "next/link";

const gayathri = Gayathri({
  variable: "--font-gayathri",
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});

const aboreto = Aboreto({
  variable: "--font-aboreto",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const menu = useRef(null);

  // const closeOpen = () => {
  //   if (openModal) {
  //     setOpenModal(false);
  //   } else {
  //     setOpenModal(true);
  //   }
  // };

  // useEffect(() => {
  //   const isMobile = window.innerWidth < 1024;

  // gsap.set(menu.current, {
  //   opacity: 0,
  //   y: 20,
  // });

  //   ScrollTrigger.create({
  //     start: 0,
  //     end: "max",
  //     onUpdate: (self) => {
  //       if (self.direction === 1) {
  //         scrollAnim.play(); // scroll down
  //       } else {
  //         scrollAnim.reverse(); // scroll up
  //       }
  //     },
  //   });

  //   return () => {
  //     ScrollTrigger.killAll();
  //   };
  // }, []);

  return (
    <html lang="en">
      <body className={`${gayathri.variable} ${aboreto.variable}  antialiased`}>
        <header className="mix-blend-difference w-full bg-transparent fixed top-0 left-0 z-10 border-b-[1px] border-solid border-[#000000] before:absolute before:w-full before:h-full before:backdrop-blur-md">
          <div className="container">
            <div className="py-4 flex bg-transparent items-center justify-between relative">
              <button
                // onClick={() => closeOpen()}
                // ref={menu}
                className="lg:hidden relative w-8 h-2 focus:outline-none"
                aria-label="Toggle menu"
              >
                <div className="relative w-full h-full flex justify-center items-center gap-2 mix-blend-difference">
                  {/* Top line */}
                  <span
                    className={`w-8 h-0.5 bg-black absolute transition-all duration-500 ease-in-out `}
                  ></span>

                  <span
                    className={`w-8 h-0.5 -mt-3 bg-black absolute transition-all duration-500 ease-in-out `}
                  ></span>
                </div>
              </button>
              <div className="flex flex-col items-center">
                <h1 className="font-aboreto text-lg lg:text-2xl text-white mix-blend-difference">
                  SUROJIDDIN
                </h1>
                <p className="font-aboreto text-lg lg:text-2xl text-white mix-blend-difference">
                  ATTOR
                </p>
              </div>

              <div>
                <button className="cursor-pointer">
                  <ShoppingBag width={26} height={26} strokeWidth={1.5} />
                </button>
              </div>
              <div className="text-xl flex gap-4 ">
                <Link className="mix-blend-difference" href={"/category"}>
                  MENS
                </Link>
                <Link href={"/category"}>WOMENS</Link>
                <Link href={"/category"}>TRENDS</Link>
                <Link href={"/category"}>SEASONS</Link>
              </div>
              <div className="lg:flex gap-4 hidden">
                <button className="cursor-pointer">
                  <Search width={26} height={26} strokeWidth={1.5} />
                </button>
                <button className="cursor-pointer">
                  <ShoppingBag width={26} height={26} strokeWidth={1.5} />
                </button>
                <button className="cursor-pointer">
                  <Instagram width={26} height={26} strokeWidth={1.5} />
                </button>
              </div>
            </div>
          </div>
        </header>
        <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
          {children}
        </main>
        <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center"></footer>
      </body>
    </html>
  );
}
